### ISSUE TITLE
Define Web Agents in server.recon file

### ISSUE THREAD

**Issue by ajay-gov** [swimos/cookbook#20]
Add a new cookbook with the following features:

- [x]  Illustrate how to define web agents using the `server.recon` file. The other examples in the cookbook use the annotation based web agent definition. Use the code from the [Web Agent cookbook](https://github.com/swimos/cookbook/tree/master/web_agents) and replace the annotations with the `server.recon` file.

- [x]  Add properties for the web agents in the `server.recon` file. Add code in the Web Agents to read the properties, will be good to show how properties of different types can be loaded i.e `String`, `int`, `float`, `boolean`. Might be good to show loading `Value` type properties as well

**Comment by AdityaRandive** [comment]
Issue addressed via commit 635841bdc516ffbc9ff493accee61296b5e3b85e. Closing this issue.
