### ISSUE TITLE
Add Demand Map Lanes companion project

### ISSUE THREAD

**Issue by brohitbrose** [swimos/cookbook#9]
- [ ] Analogize a large `.csv` file to a database

- [ ] Introduce a `MapLane`/`DemandMapLane` pairing that reflects data in this "database"

**Comment by ajay-gov** [comment]
Superseded by issue #11

**Comment by ajay-gov** [comment]
@brohitbrose ok to use issue #11 to track this and close this issue? We will cover `DemandLanes` in general there. The specific application maybe different
